-- MindBridge — αρχικό σχήμα για Supabase Postgres.
-- Εφαρμογή:  npm run db:migrate   (ή: psql "$DATABASE_URL" -f αυτό το αρχείο)
--
-- Σημείωση για τα flags (notify_email, booked, faith_based, ...): κρατιούνται
-- integer 0/1 όπως στη SQLite, ώστε ο ίδιος κώδικας ερωτημάτων να δουλεύει και
-- στις δύο βάσεις χωρίς μεταφράσεις τύπων.

create table if not exists users (
  id                bigint generated by default as identity primary key,
  email             text unique not null,
  auth_id           uuid unique references auth.users(id) on delete set null,
  password_hash     text,
  role              text not null default 'client' check (role in ('client','therapist','admin')),
  display_name      text not null,
  nickname          text,
  phone             text,
  timezone          text default 'Europe/Athens',
  locale            text default 'el',
  emergency_contact text,
  notify_email      integer default 1,
  notify_sms        integer default 0,
  created_at        timestamptz default now()
);

create table if not exists therapists (
  id                bigint generated by default as identity primary key,
  user_id           bigint unique not null references users(id) on delete cascade,
  headline          text,
  bio               text,
  credentials       text,
  license_no        text unique,
  years_experience  integer default 0,
  gender            text,
  languages         text default 'el',
  specialties       text default '',
  approaches        text default '',
  faith_based       integer default 0,
  lgbtq_friendly    integer default 1,
  photo             text,
  rating            real default 5,
  reviews_count     integer default 0,
  accepting_clients integer default 1,
  max_clients       integer default 25,
  avg_response_hours integer default 8,
  status            text not null default 'approved' check (status in ('pending','approved','rejected')),
  applied_at        timestamptz,
  reviewed_at       timestamptz,
  review_note       text
);

create table if not exists intakes (
  id         bigint generated by default as identity primary key,
  user_id    bigint references users(id) on delete cascade,
  anon_token text,
  service    text default 'individual',
  answers    text not null,
  risk_level text default 'low',
  created_at timestamptz default now()
);

create table if not exists assessments (
  id         bigint generated by default as identity primary key,
  user_id    bigint not null references users(id) on delete cascade,
  answers    text not null,
  scores     text not null,
  risk_level text default 'low',
  created_at timestamptz default now()
);

create table if not exists matches (
  id           bigint generated by default as identity primary key,
  client_id    bigint not null references users(id) on delete cascade,
  therapist_id bigint not null references therapists(id) on delete cascade,
  status       text not null default 'active' check (status in ('active','ended')),
  score        real default 0,
  reason       text,
  started_at   timestamptz default now(),
  ended_at     timestamptz
);

create table if not exists rooms (
  id         bigint generated by default as identity primary key,
  match_id   bigint not null references matches(id) on delete cascade,
  created_at timestamptz default now()
);

create table if not exists messages (
  id         bigint generated by default as identity primary key,
  room_id    bigint not null references rooms(id) on delete cascade,
  sender_id  bigint not null references users(id) on delete cascade,
  body       text not null,
  kind       text default 'text',
  meta       text,
  read_at    timestamptz,
  created_at timestamptz default now()
);

create table if not exists availability (
  id           bigint generated by default as identity primary key,
  therapist_id bigint not null references therapists(id) on delete cascade,
  starts_at    timestamptz not null,
  duration_min integer default 45,
  modality     text default 'video',
  booked       integer default 0
);

create table if not exists sessions (
  id           bigint generated by default as identity primary key,
  match_id     bigint not null references matches(id) on delete cascade,
  slot_id      bigint references availability(id) on delete set null,
  starts_at    timestamptz not null,
  duration_min integer default 45,
  modality     text default 'video',
  status       text default 'scheduled' check (status in ('scheduled','completed','cancelled','no_show')),
  join_code    text,
  notes        text,
  created_at   timestamptz default now()
);

create table if not exists journal_entries (
  id                     bigint generated by default as identity primary key,
  user_id                bigint not null references users(id) on delete cascade,
  title                  text,
  body                   text,
  mood                   integer check (mood between 1 and 5),
  shared_with_therapist  integer default 0,
  created_at             timestamptz default now()
);

create table if not exists worksheets (
  id          bigint generated by default as identity primary key,
  slug        text unique not null,
  title       text not null,
  category    text,
  description text,
  fields      text not null
);

create table if not exists worksheet_assignments (
  id           bigint generated by default as identity primary key,
  worksheet_id bigint not null references worksheets(id) on delete cascade,
  client_id    bigint not null references users(id) on delete cascade,
  assigned_by  bigint references users(id) on delete set null,
  status       text default 'assigned' check (status in ('assigned','completed')),
  answers      text,
  assigned_at  timestamptz default now(),
  completed_at timestamptz
);

create table if not exists groupinars (
  id                bigint generated by default as identity primary key,
  title             text not null,
  topic             text,
  host_therapist_id bigint references therapists(id) on delete set null,
  starts_at         timestamptz not null,
  duration_min      integer default 60,
  description       text,
  capacity          integer default 200
);

create table if not exists groupinar_registrations (
  id           bigint generated by default as identity primary key,
  groupinar_id bigint not null references groupinars(id) on delete cascade,
  user_id      bigint not null references users(id) on delete cascade,
  created_at   timestamptz default now(),
  unique (groupinar_id, user_id)
);

create table if not exists subscriptions (
  id             bigint generated by default as identity primary key,
  user_id        bigint unique not null references users(id) on delete cascade,
  plan           text not null default 'standard',
  billing_period text default 'monthly',
  price_cents    integer not null,
  discount_pct   integer default 0,
  status         text default 'trialing' check (status in ('trialing','active','paused','cancelled')),
  renews_at      timestamptz,
  cancelled_at   timestamptz,
  created_at     timestamptz default now()
);

create table if not exists payments (
  id           bigint generated by default as identity primary key,
  user_id      bigint not null references users(id) on delete cascade,
  amount_cents integer not null,
  description  text,
  status       text default 'paid',
  created_at   timestamptz default now()
);

create table if not exists financial_aid (
  id                   bigint generated by default as identity primary key,
  user_id              bigint not null references users(id) on delete cascade,
  monthly_income_cents bigint,
  household_size       integer,
  employment           text,
  status               text default 'approved',
  discount_pct         integer default 0,
  created_at           timestamptz default now()
);

create table if not exists reviews (
  id           bigint generated by default as identity primary key,
  therapist_id bigint not null references therapists(id) on delete cascade,
  client_id    bigint references users(id) on delete set null,
  rating       integer not null check (rating between 1 and 5),
  body         text,
  author_label text,
  created_at   timestamptz default now()
);

create table if not exists notifications (
  id         bigint generated by default as identity primary key,
  user_id    bigint not null references users(id) on delete cascade,
  title      text not null,
  body       text,
  link       text,
  read_at    timestamptz,
  created_at timestamptz default now()
);

create index if not exists idx_messages_room     on messages(room_id, id);
create index if not exists idx_matches_client    on matches(client_id, status);
create index if not exists idx_avail_therapist   on availability(therapist_id, starts_at);
create index if not exists idx_assessments_user  on assessments(user_id, id);
create index if not exists idx_notifications_user on notifications(user_id, id);
create index if not exists idx_users_auth        on users(auth_id);

-- Ασφάλεια: κάθε πίνακας κλειδώνεται με RLS χωρίς πολιτικές, ώστε οι ρόλοι
-- anon/authenticated του Supabase (δηλαδή το PostgREST API με το anon key) να
-- μη βλέπουν τίποτα. Η εφαρμογή συνδέεται με τον ιδιοκτήτη του σχήματος μέσω
-- DATABASE_URL και περνά από τους δικούς της ελέγχους δικαιωμάτων.
do $$
declare t text;
begin
  foreach t in array array[
    'users','therapists','intakes','assessments','matches','rooms','messages','availability',
    'sessions','journal_entries','worksheets','worksheet_assignments','groupinars',
    'groupinar_registrations','subscriptions','payments','financial_aid','reviews','notifications'
  ] loop
    execute format('alter table %I enable row level security', t);
    execute format('revoke all on table %I from anon, authenticated', t);
  end loop;
end $$;
